alias ls='ls --color=auto --group-directories-first -h'
alias cp='cp -iv'
alias ln='ln -iv'
alias mv='mv -iv'
alias rm='rm -I --preserve-root'
alias rmdir='rmdir -v'
alias grep='grep --color=auto'
alias mkdir='mkdir -vp'
alias v='nvim'
alias ll='ls -la'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
